export const QUILL_MODULES = {
  toolbar: [
    [{ size: ["small", false, "large", "huge"] }],
    ["bold", "italic", "underline", "strike", "blockquote"],
    [{ color: [] }, { background: [] }],
    [{ list: "ordered" }, { list: "bullet" }],
    ["link"],
    ["clean"],
  ],
};
export const TOOLBAR_TOOLTIPS = {
  size: "Font Size",
  bold: "Bold",
  italic: "Italic",
  underline: "Underline",
  strike: "Strikethrough",
  blockquote: "Quote",
  "code-block": "Code Block",
  link: "Insert Link",
  image: "Insert Image",
  list: {
    ordered: "Numbered List",
    bullet: "Bulleted List",
  },
  indent: {
    "+1": "Increase Indent",
    "-1": "Decrease Indent",
  },
  header: {
    1: "Heading 1",
    2: "Heading 2",
  },
  color: "Text Color",
  background: "Background Color",
  align: "Text Alignment",
  clean: "Clear Formatting",
  emoji: "Insert Emoji",
};

export const COLOR_NAMES = {
  "#DBA42D": "Golden Amber",
  "#D2691E": "Chocolate",
  "#292929": "Charcoal",
  "#4B0082": "Indigo",
  "#F5F5DC": "Beige",
  "#191919": "Pitch Black",
  "#ffadad": "Light Coral",
  "#ffdda1": "Light Yellow",
  "#d4aaff": "Light Purple",
  "#85e6c5": "Light Teal",
  "#b1e5fc": "Light Blue",
  "#ffffff": "White",
  "#FF0000": "Red",
  "#0000FF": "Blue",
  "#00FF00": "Green",
  "#FFFF00": "Yellow",
  "#800080": "Purple",
  "#FFA500": "Orange",
  "#FFC0CB": "Pink",
  "#008080": "Teal",
  "#000080": "Navy",
  "#800000": "Maroon",
  "#808000": "Olive",
  "#808080": "Gray",
  "#000000": "Black",
  "#FFFFFF": "White",
  "#A52A2A": "Brown",
  "#00FFFF": "Cyan",
  "#FF7F50": "Coral",
  "#E6E6FA": "Lavender",
  "#87CEEB": "Sky Blue",
  "#FF1493": "Deep Pink",
  "#FFD700": "Gold",
  "#32CD32": "Lime Green",
};
