export const AUTHORIZED_MINTS = [
  { id: 1, name: "Argor Hereaus" },
  { id: 2, name: "Highland Mint" },
  { id: 3, name: "Regency Mint" },
  { id: 4, name: "Asahi" },
  { id: 5, name: "Italpreziosi" },
  { id: 6, name: "Royal Canadian Mint" },
  { id: 7, name: "Austrian Mint" },
  { id: 8, name: "JBR" },
  { id: 9, name: "Royal Mint (UK)" },
  { id: 10, name: "Chinese Mint" },
  { id: 11, name: "Johnson Matthey" },
  { id: 12, name: "Royal Mint of Belgium" },
  { id: 13, name: "Colombian Mint" },
  { id: 14, name: "Mexican Mint" },
  { id: 15, name: "SilverTowne" },
  { id: 16, name: "Copenhagen Mint" },
  { id: 17, name: "Monnaie de Paris" },
  { id: 18, name: "Sunshine Mint" },
  { id: 19, name: "Dutch Royal Mint" },
  { id: 20, name: "New Zealand Mint" },
  { id: 21, name: "Swissmint" },
  { id: 22, name: "Engelhard" },
  { id: 23, name: "PAMP" },
  { id: 24, name: "Tokuriki Honten" },
  { id: 25, name: "Germania Mint" },
  { id: 26, name: "Perth Mint" },
  { id: 27, name: "US Mint" },
  { id: 28, name: "Golden State Mint" },
  { id: 29, name: "Rand Refinery" },
  { id: 30, name: "Valcambi" },
];
